#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Syncs Notion databases into the al-folio data files of this site.

Reads four Notion databases (Research, Projects, CV Entries, Patents) through the
REST API and regenerates three site artifacts:

  * ``_bibliography/papers.bib``  -- publications rendered by jekyll-scholar
  * ``_projects/*.md``            -- project cards (generated files only)
  * ``_data/cv.yml``              -- RenderCV-format CV data

Notion is read-only here. Only rows with the ``공개`` checkbox set are exported,
unless ``--all`` is passed. Output is deterministic: entries are sorted and no
timestamps are written, so an unchanged Notion state produces an empty diff.

Usage:
    uv run --script scripts/notion_sync.py [--all] [--check]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import unicodedata
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import yaml

NOTION_API = "https://api.notion.com"
NOTION_VERSION = "2022-06-28"

RESEARCH_DB = "3b632e6de3498120977bc5f150207ed0"
PROJECTS_DB = "3b632e6de349815d8d5ee56da843fad0"
CV_DB = "3b632e6de34981909465cb0af5e04e9f"
PATENTS_DB = "3b632e6de3498179bda0f56414ac7afe"

REPO_ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = REPO_ROOT / "_bibliography" / "papers.bib"
PROJECTS_DIR = REPO_ROOT / "_projects"
CV_PATH = REPO_ROOT / "_data" / "cv.yml"

# Marks files this script owns, so a rerun can clear them without touching
# anything a human added to _projects/.
GENERATED_MARKER = (
    "<!-- generated by scripts/notion_sync.py from Notion; do not edit -->"
)

# Publication type (유형) -> (BibTeX entry type, field holding the venue).
PUBLICATION_TYPES = {
    "Journal": ("article", "journal"),
    "International Conference": ("inproceedings", "booktitle"),
    "Domestic Conference": ("inproceedings", "booktitle"),
    "Workshop": ("inproceedings", "booktitle"),
    "Preprint": ("misc", None),
}

# Project category (분류) -> al-folio project category.
PROJECT_CATEGORIES = {
    "Industry Collaboration": "industry",
    "Funded Research": "funded",
    "Personal": "personal",
}
DEFAULT_PROJECT_CATEGORY = "project"
RESEARCH_PROJECT_CATEGORY = "research"

CV_OWNER_NAME = "Sungsoo Lee"
CV_OWNER_LABEL = (
    "Ph.D. Student, Department of Data Science, "
    "Seoul National University of Science and Technology (SeoulTech)"
)
CV_OWNER_EMAIL = "sungsoo207@seoultech.ac.kr"


# -----------------------------------------------------------------------------
# Notion access
# -----------------------------------------------------------------------------


def read_token() -> str:
    """Returns the Notion integration token from env or the macOS keychain."""
    token = os.environ.get("NOTION_TOKEN")
    if token:
        return token.strip()
    result = subprocess.run(
        [
            "security",
            "find-generic-password",
            "-a",
            os.environ["USER"],
            "-s",
            "notion-api-token",
            "-w",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(
            "no Notion token: set NOTION_TOKEN or add the keychain item notion-api-token"
        )
    return result.stdout.strip()


def query_database(token: str, database_id: str) -> list[dict[str, Any]]:
    """Returns every page of a Notion database, following pagination."""
    rows: list[dict[str, Any]] = []
    cursor: str | None = None
    while True:
        payload: dict[str, Any] = {"page_size": 100}
        if cursor:
            payload["start_cursor"] = cursor
        request = urllib.request.Request(
            f"{NOTION_API}/v1/databases/{database_id}/query",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {token}",
                "Notion-Version": NOTION_VERSION,
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request) as response:
                body = json.load(response)
        except urllib.error.HTTPError as error:
            raise SystemExit(
                f"Notion query failed for {database_id}: "
                f"{error.code} {error.read().decode('utf-8', 'replace')}"
            ) from error
        rows.extend(body["results"])
        if not body.get("has_more"):
            return rows
        cursor = body["next_cursor"]


# -----------------------------------------------------------------------------
# Property accessors
# -----------------------------------------------------------------------------


def text_of(row: dict[str, Any], name: str) -> str:
    """Returns a title or rich_text property as plain text."""
    prop = row["properties"].get(name)
    if not prop:
        return ""
    kind = prop["type"]
    if kind not in ("title", "rich_text"):
        return ""
    return "".join(part["plain_text"] for part in prop[kind]).strip()


def select_of(row: dict[str, Any], name: str) -> str:
    """Returns a select property name, or an empty string."""
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "select" or not prop["select"]:
        return ""
    return prop["select"]["name"]


def number_of(row: dict[str, Any], name: str) -> int | float | None:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "number":
        return None
    return prop["number"]


def checkbox_of(row: dict[str, Any], name: str) -> bool:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "checkbox":
        return False
    return bool(prop["checkbox"])


def url_of(row: dict[str, Any], name: str) -> str:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "url" or not prop["url"]:
        return ""
    return prop["url"]


def date_of(row: dict[str, Any], name: str) -> tuple[str, str]:
    """Returns the (start, end) ISO strings of a date property."""
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "date" or not prop["date"]:
        return "", ""
    return prop["date"].get("start") or "", prop["date"].get("end") or ""


def is_public(row: dict[str, Any]) -> bool:
    return checkbox_of(row, "공개")


def english_title(row: dict[str, Any], title_field: str) -> str:
    """Returns the English title when present, else the native title."""
    return text_of(row, "Title (EN)") or text_of(row, title_field)


# -----------------------------------------------------------------------------
# Shared helpers
# -----------------------------------------------------------------------------


def dump_yaml(data: dict[str, Any]) -> str:
    """Dumps YAML in insertion order, unwrapped, so diffs stay line-stable."""
    return yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=10000,
    )


def slugify(text: str) -> str:
    """Returns a lowercase ASCII slug; non-ASCII characters are dropped."""
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^A-Za-z0-9]+", "-", ascii_text).strip("-").lower()


def short_id(row: dict[str, Any]) -> str:
    """Returns a stable short identifier derived from the Notion page id."""
    return row["id"].replace("-", "")[:8]


def format_year_month(iso_date: str) -> str:
    """Formats an ISO date as YYYY.MM."""
    parts = iso_date.split("-")
    if len(parts) >= 2:
        return f"{parts[0]}.{parts[1]}"
    return parts[0]


# -----------------------------------------------------------------------------
# papers.bib
# -----------------------------------------------------------------------------


def bib_key(authors: str, year: int | None, title: str, taken: set[str]) -> str:
    """Builds a `<surname>_<year>_<first title word>` key, unique within `taken`."""
    first_author = authors.split(",")[0].strip()
    surname = slugify(first_author.split()[-1]) if first_author else "unknown"
    first_word = next((word for word in slugify(title).split("-") if word), "untitled")
    base = (
        f"{surname or 'unknown'}_{year if year is not None else 'nodate'}_{first_word}"
    )
    key = base
    suffix = 2
    while key in taken:
        key = f"{base}_{suffix}"
        suffix += 1
    taken.add(key)
    return key


def format_authors(authors: str) -> str:
    """Converts a comma-separated author list into BibTeX `A and B` form."""
    names = [name.strip() for name in authors.split(",") if name.strip()]
    return " and ".join(names)


def build_bibliography(research_rows: list[dict[str, Any]]) -> tuple[str, int]:
    """Renders the publication rows as a BibTeX file body."""
    entries: list[tuple[int, str, dict[str, Any]]] = []
    for row in research_rows:
        kind = select_of(row, "유형")
        if kind not in PUBLICATION_TYPES or select_of(row, "상태") == "Working":
            continue
        title = english_title(row, "제목")
        year = number_of(row, "연도")
        entries.append((-int(year) if year is not None else 1, title, row))
    entries.sort(key=lambda item: (item[0], item[1]))

    taken: set[str] = set()
    blocks: list[str] = []
    for _, title, row in entries:
        entry_type, venue_field = PUBLICATION_TYPES[select_of(row, "유형")]
        year = number_of(row, "연도")
        authors = text_of(row, "저자")
        url = url_of(row, "URL")

        fields: list[tuple[str, str]] = []
        abbr = text_of(row, "약칭")
        if abbr:
            fields.append(("abbr", abbr))
        fields.append(("title", title))
        if authors:
            fields.append(("author", format_authors(authors)))
        if venue_field and text_of(row, "게재처"):
            fields.append((venue_field, text_of(row, "게재처")))
        if year is not None:
            fields.append(("year", str(int(year))))
        doi = text_of(row, "DOI")
        if doi:
            fields.append(("doi", doi))
        if url:
            fields.append(("url", url))
            fields.append(("html", url))
        if checkbox_of(row, "대표"):
            fields.append(("selected", "true"))

        width = max(len(name) for name, _ in fields)
        lines = [f"@{entry_type}{{{bib_key(authors, year, title, taken)},"]
        lines += [f"  {name.ljust(width)} = {{{value}}}," for name, value in fields]
        lines.append("}")
        blocks.append("\n".join(lines))

    return "---\n---\n\n" + "\n\n".join(blocks) + ("\n" if blocks else ""), len(blocks)


# -----------------------------------------------------------------------------
# _projects
# -----------------------------------------------------------------------------


def project_description(institution: str, start: str, end: str) -> str:
    """Builds `institution · YYYY.MM – YYYY.MM`; empty when there is no institution."""
    if not institution:
        return ""
    if not start:
        return institution
    period = format_year_month(start)
    if end:
        period = f"{period} – {format_year_month(end)}"
    return f"{institution} · {period}"


def build_projects(
    project_rows: list[dict[str, Any]], research_rows: list[dict[str, Any]]
) -> list[tuple[str, str]]:
    """Renders project cards as (filename, content) pairs.

    Sources are the Projects database and the Co-work rows of the Research
    database. Project bodies stay empty; only the front matter carries data.
    """
    drafts: list[dict[str, Any]] = []

    ordered_projects = sorted(
        project_rows,
        key=lambda row: (
            number_of(row, "중요도") is None,
            number_of(row, "중요도") or 0,
            english_title(row, "프로젝트명"),
        ),
    )
    for row in ordered_projects:
        start, end = date_of(row, "기간")
        drafts.append(
            {
                "row": row,
                "title": english_title(row, "프로젝트명"),
                "description": project_description(
                    text_of(row, "기관·발주처"), start, end
                ),
                "importance": number_of(row, "중요도"),
                "category": PROJECT_CATEGORIES.get(
                    select_of(row, "분류"), DEFAULT_PROJECT_CATEGORY
                ),
            }
        )

    cowork_rows = [row for row in research_rows if select_of(row, "참여") == "Co-work"]
    ordered_cowork = sorted(
        cowork_rows,
        key=lambda row: (
            -int(number_of(row, "연도") or 0),
            english_title(row, "제목"),
        ),
    )
    for row in ordered_cowork:
        drafts.append(
            {
                "row": row,
                "title": english_title(row, "제목"),
                "description": "",
                "importance": None,
                "category": RESEARCH_PROJECT_CATEGORY,
            }
        )

    files: list[tuple[str, str]] = []
    used_slugs: set[str] = set()
    for index, draft in enumerate(drafts, start=1):
        front_matter: dict[str, Any] = {
            "layout": "page",
            "title": draft["title"],
        }
        if draft["description"]:
            front_matter["description"] = draft["description"]
        importance = draft["importance"]
        front_matter["importance"] = (
            int(importance) if importance is not None else index
        )
        front_matter["category"] = draft["category"]

        slug = slugify(draft["title"]) or short_id(draft["row"])
        if slug in used_slugs:
            slug = f"{slug}-{short_id(draft['row'])}"
        used_slugs.add(slug)

        body = dump_yaml(front_matter)
        files.append((f"{slug}.md", f"---\n{body}---\n\n{GENERATED_MARKER}\n"))
    return files


def write_projects(files: list[tuple[str, str]]) -> None:
    """Replaces the generated project files, leaving hand-written ones alone."""
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    for path in PROJECTS_DIR.glob("*.md"):
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
    for name, content in files:
        (PROJECTS_DIR / name).write_text(content, encoding="utf-8")


# -----------------------------------------------------------------------------
# _data/cv.yml
# -----------------------------------------------------------------------------


def build_cv(
    cv_rows: list[dict[str, Any]], patent_rows: list[dict[str, Any]]
) -> dict[str, Any]:
    """Builds the RenderCV-format CV data consumed by the al_folio_cv plugin."""
    sections: dict[str, list[dict[str, Any]]] = {}

    def by_recency(row: dict[str, Any], title_field: str) -> tuple[str, str]:
        start, _ = date_of(row, "기간")
        # Sorting on the negated ISO string is awkward, so reverse later instead.
        return (start or "", text_of(row, title_field))

    def dated_rows(kind: str) -> list[dict[str, Any]]:
        rows = [row for row in cv_rows if select_of(row, "구분") == kind]
        return sorted(rows, key=lambda row: by_recency(row, "내용"), reverse=True)

    education: list[dict[str, Any]] = []
    for row in dated_rows("Education"):
        start, end = date_of(row, "기간")
        entry: dict[str, Any] = {"studyType": text_of(row, "내용")}
        if text_of(row, "기관"):
            entry["institution"] = text_of(row, "기관")
        if start:
            entry["start_date"] = start
        if end:
            entry["end_date"] = end
        if text_of(row, "비고"):
            entry["highlights"] = [text_of(row, "비고")]
        education.append(entry)
    if education:
        sections["Education"] = education

    experience: list[dict[str, Any]] = []
    for row in dated_rows("Experience"):
        start, end = date_of(row, "기간")
        entry = {"position": text_of(row, "내용")}
        if text_of(row, "기관"):
            entry["company"] = text_of(row, "기관")
        if start:
            entry["start_date"] = start
        if end:
            entry["end_date"] = end
        if text_of(row, "비고"):
            entry["highlights"] = [text_of(row, "비고")]
        experience.append(entry)
    if experience:
        sections["Experience"] = experience

    awards: list[dict[str, Any]] = []
    for row in dated_rows("Award"):
        start, _ = date_of(row, "기간")
        entry = {"title": text_of(row, "내용")}
        if start:
            entry["date"] = start
        if text_of(row, "기관"):
            entry["awarder"] = text_of(row, "기관")
        if text_of(row, "비고"):
            entry["summary"] = text_of(row, "비고")
        awards.append(entry)
    if awards:
        sections["Honors and Awards"] = awards

    patents: list[dict[str, Any]] = []
    ordered_patents = sorted(
        patent_rows,
        key=lambda row: (date_of(row, "출원일")[0], text_of(row, "발명의 명칭")),
        reverse=True,
    )
    for row in ordered_patents:
        head = " ".join(
            part for part in (select_of(row, "국가"), text_of(row, "출원번호")) if part
        )
        tail = ", ".join(part for part in (head, select_of(row, "상태")) if part)
        title = text_of(row, "발명의 명칭")
        patents.append({"bullet": f"{title} — {tail}" if tail else title})
    if patents:
        sections["Patents"] = patents

    skills: list[dict[str, Any]] = []
    skill_rows = sorted(
        (row for row in cv_rows if select_of(row, "구분") == "Skill"),
        key=lambda row: text_of(row, "내용"),
    )
    for row in skill_rows:
        entry = {"name": text_of(row, "내용")}
        keywords = [
            part.strip() for part in text_of(row, "비고").split(",") if part.strip()
        ]
        if keywords:
            entry["keywords"] = keywords
        skills.append(entry)
    if skills:
        sections["Skills"] = skills

    cv: dict[str, Any] = {
        "name": CV_OWNER_NAME,
        "label": CV_OWNER_LABEL,
        "email": CV_OWNER_EMAIL,
    }
    if sections:
        cv["sections"] = sections
    return {"cv": cv}


# -----------------------------------------------------------------------------
# Sync and self-check
# -----------------------------------------------------------------------------


def sync(include_private: bool) -> dict[str, int]:
    """Regenerates every artifact and returns the number of rows written."""
    token = read_token()
    research = query_database(token, RESEARCH_DB)
    projects = query_database(token, PROJECTS_DB)
    cv_entries = query_database(token, CV_DB)
    patents = query_database(token, PATENTS_DB)

    if not include_private:
        research = [row for row in research if is_public(row)]
        projects = [row for row in projects if is_public(row)]
        cv_entries = [row for row in cv_entries if is_public(row)]
        patents = [row for row in patents if is_public(row)]

    bib_text, bib_count = build_bibliography(research)
    BIB_PATH.parent.mkdir(parents=True, exist_ok=True)
    BIB_PATH.write_text(bib_text, encoding="utf-8")

    project_files = build_projects(projects, research)
    write_projects(project_files)

    cv_data = build_cv(cv_entries, patents)
    CV_PATH.parent.mkdir(parents=True, exist_ok=True)
    CV_PATH.write_text(
        dump_yaml(cv_data),
        encoding="utf-8",
    )

    return {
        "publications": bib_count,
        "projects": len(project_files),
        "cv_sections": len(cv_data["cv"].get("sections", {})),
    }


def check() -> list[str]:
    """Re-reads the generated artifacts and returns a list of problems found."""
    problems: list[str] = []

    if not BIB_PATH.exists():
        problems.append(f"missing {BIB_PATH.relative_to(REPO_ROOT)}")
    else:
        text = BIB_PATH.read_text(encoding="utf-8")
        entries = re.findall(r"^@\w+\{", text, flags=re.MULTILINE)
        if not text.endswith("\n"):
            problems.append("papers.bib does not end with a newline")
        print(f"  papers.bib: {len(entries)} entries")

    if not CV_PATH.exists():
        problems.append(f"missing {CV_PATH.relative_to(REPO_ROOT)}")
    else:
        try:
            data = yaml.safe_load(CV_PATH.read_text(encoding="utf-8"))
        except yaml.YAMLError as error:
            problems.append(f"cv.yml does not parse: {error}")
        else:
            if not isinstance(data, dict) or "cv" not in data:
                problems.append("cv.yml has no top-level 'cv' key")
            else:
                names = list(data["cv"].get("sections", {}))
                print(f"  cv.yml: {len(names)} sections {names}")

    generated = sorted(
        path
        for path in PROJECTS_DIR.glob("*.md")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")
    )
    for path in generated:
        text = path.read_text(encoding="utf-8")
        match = re.match(r"^---\n(.*?)\n---\n", text, flags=re.DOTALL)
        if not match:
            problems.append(f"{path.name}: no front matter")
            continue
        try:
            front_matter = yaml.safe_load(match.group(1))
        except yaml.YAMLError as error:
            problems.append(f"{path.name}: front matter does not parse: {error}")
            continue
        for field in ("layout", "title", "importance", "category"):
            if field not in front_matter:
                problems.append(f"{path.name}: front matter is missing '{field}'")
    print(f"  _projects: {len(generated)} generated files")

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--all",
        action="store_true",
        help="include rows whose 공개 checkbox is off (preview only, do not commit)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files after syncing and exit non-zero on failure",
    )
    args = parser.parse_args()

    counts = sync(include_private=args.all)
    scope = "all rows" if args.all else "public rows"
    print(
        f"synced {scope}: {counts['publications']} publications, "
        f"{counts['projects']} projects, {counts['cv_sections']} CV sections"
    )

    if not args.check:
        return 0

    print("checking generated files")
    problems = check()
    if problems:
        for problem in problems:
            print(f"  FAIL {problem}", file=sys.stderr)
        return 1
    print("check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
