#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Syncs Notion databases into the al-folio data files of this site.

Reads four Notion databases (Research, Projects, CV Entries, Patents) through the
REST API and regenerates six site artifacts:

  * ``_bibliography/papers.bib``  -- publications rendered by jekyll-scholar
  * ``_projects/*.md``            -- project cards (generated files only)
  * ``_data/education.yml``       -- education list for the home tab
  * ``_data/honors.yml``          -- honors and their amounts, for the home tab
  * ``_data/patents.yml``         -- patent list for the research tab
  * ``_data/presentations.yml``   -- talks and posters for the research tab

Notion is read-only here. Only rows with the ``공개`` checkbox set are exported,
unless ``--all`` is passed. Output is deterministic: entries are sorted and no
timestamps are written, so an unchanged Notion state produces an empty diff.

Usage:
    uv run --script scripts/notion_sync.py [--all] [--check]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import unicodedata
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

import yaml

NOTION_API = "https://api.notion.com"
NOTION_VERSION = "2022-06-28"

RESEARCH_DB = "3b632e6de3498120977bc5f150207ed0"
PROJECTS_DB = "3b632e6de349815d8d5ee56da843fad0"
CV_DB = "3b632e6de34981909465cb0af5e04e9f"
PATENTS_DB = "3b632e6de3498179bda0f56414ac7afe"

REPO_ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = REPO_ROOT / "_bibliography" / "papers.bib"
PROJECTS_DIR = REPO_ROOT / "_projects"
EDUCATION_PATH = REPO_ROOT / "_data" / "education.yml"
HONORS_PATH = REPO_ROOT / "_data" / "honors.yml"
PATENTS_PATH = REPO_ROOT / "_data" / "patents.yml"
PRESENTATIONS_PATH = REPO_ROOT / "_data" / "presentations.yml"

# Marks files this script owns, so a rerun can clear them without touching
# anything a human added to _projects/.
GENERATED_MARKER = (
    "<!-- generated by scripts/notion_sync.py from Notion; do not edit -->"
)

# Rows in these states are not published papers yet and stay out of papers.bib.
EXCLUDED_STATUSES = frozenset({"Working", "Under Review"})

# Publication type (유형) -> (BibTeX entry type, field holding the venue, label
# shown as the type pill on the home page via the custom `pubtype` field).
PUBLICATION_TYPES = {
    "Journal": ("article", "journal", "Journal"),
    "International Conference": ("inproceedings", "booktitle", "Intl. Conf."),
    "Workshop": ("inproceedings", "booktitle", "Workshop"),
    "Preprint": ("misc", None, "Preprint"),
}

# Project category (분류) -> al-folio project category.
PROJECT_CATEGORIES = {
    "Industry Collaboration": "industry",
    "Funded Research": "funded",
    "Personal": "personal",
}
DEFAULT_PROJECT_CATEGORY = "project"
RESEARCH_PROJECT_CATEGORY = "research"


# -----------------------------------------------------------------------------
# Notion access
# -----------------------------------------------------------------------------


def read_token() -> str:
    """Returns the Notion integration token from env or the macOS keychain."""
    token = os.environ.get("NOTION_TOKEN")
    if token:
        return token.strip()
    result = subprocess.run(
        [
            "security",
            "find-generic-password",
            "-a",
            os.environ["USER"],
            "-s",
            "notion-api-token",
            "-w",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise SystemExit(
            "no Notion token: set NOTION_TOKEN or add the keychain item notion-api-token"
        )
    return result.stdout.strip()


def query_database(token: str, database_id: str) -> list[dict[str, Any]]:
    """Returns every page of a Notion database, following pagination."""
    rows: list[dict[str, Any]] = []
    cursor: str | None = None
    while True:
        payload: dict[str, Any] = {"page_size": 100}
        if cursor:
            payload["start_cursor"] = cursor
        request = urllib.request.Request(
            f"{NOTION_API}/v1/databases/{database_id}/query",
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {token}",
                "Notion-Version": NOTION_VERSION,
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request) as response:
                body = json.load(response)
        except urllib.error.HTTPError as error:
            raise SystemExit(
                f"Notion query failed for {database_id}: "
                f"{error.code} {error.read().decode('utf-8', 'replace')}"
            ) from error
        rows.extend(body["results"])
        if not body.get("has_more"):
            return rows
        cursor = body["next_cursor"]


# -----------------------------------------------------------------------------
# Property accessors
# -----------------------------------------------------------------------------


def text_of(row: dict[str, Any], name: str) -> str:
    """Returns a title or rich_text property as plain text."""
    prop = row["properties"].get(name)
    if not prop:
        return ""
    kind = prop["type"]
    if kind not in ("title", "rich_text"):
        return ""
    return "".join(part["plain_text"] for part in prop[kind]).strip()


def select_of(row: dict[str, Any], name: str) -> str:
    """Returns a select property name, or an empty string."""
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "select" or not prop["select"]:
        return ""
    return prop["select"]["name"]


def number_of(row: dict[str, Any], name: str) -> int | float | None:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "number":
        return None
    return prop["number"]


def checkbox_of(row: dict[str, Any], name: str) -> bool:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "checkbox":
        return False
    return bool(prop["checkbox"])


def url_of(row: dict[str, Any], name: str) -> str:
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "url" or not prop["url"]:
        return ""
    return prop["url"]


def date_of(row: dict[str, Any], name: str) -> tuple[str, str]:
    """Returns the (start, end) ISO strings of a date property."""
    prop = row["properties"].get(name)
    if not prop or prop["type"] != "date" or not prop["date"]:
        return "", ""
    return prop["date"].get("start") or "", prop["date"].get("end") or ""


def is_public(row: dict[str, Any]) -> bool:
    return checkbox_of(row, "공개")


def english_title(row: dict[str, Any], title_field: str) -> str:
    """Returns the English title when present, else the native title."""
    return text_of(row, "Title (EN)") or text_of(row, title_field)


# -----------------------------------------------------------------------------
# Shared helpers
# -----------------------------------------------------------------------------


def dump_yaml(data: dict[str, Any]) -> str:
    """Dumps YAML in insertion order, unwrapped, so diffs stay line-stable."""
    return yaml.safe_dump(
        data,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=10000,
    )


def slugify(text: str) -> str:
    """Returns a lowercase ASCII slug; non-ASCII characters are dropped."""
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    return re.sub(r"[^A-Za-z0-9]+", "-", ascii_text).strip("-").lower()


def short_id(row: dict[str, Any]) -> str:
    """Returns a stable short identifier derived from the Notion page id."""
    return row["id"].replace("-", "")[:8]


def format_year_month(iso_date: str) -> str:
    """Formats an ISO date as YYYY.MM."""
    parts = iso_date.split("-")
    if len(parts) >= 2:
        return f"{parts[0]}.{parts[1]}"
    return parts[0]


def format_period(start: str, end: str, ongoing: bool) -> str:
    """Builds `YYYY.MM – YYYY.MM`; empty when there is no start date.

    An `ongoing` entry without an end date reads `YYYY.MM – present`.
    """
    if not start:
        return ""
    period = format_year_month(start)
    if end:
        return f"{period} – {format_year_month(end)}"
    if ongoing:
        return f"{period} – present"
    return period


# -----------------------------------------------------------------------------
# papers.bib
# -----------------------------------------------------------------------------


def bib_key(authors: str, year: int | None, title: str, taken: set[str]) -> str:
    """Builds a `<surname>_<year>_<first title word>` key, unique within `taken`."""
    first_author = authors.split(",")[0].strip()
    surname = slugify(first_author.split()[-1]) if first_author else "unknown"
    first_word = next((word for word in slugify(title).split("-") if word), "untitled")
    base = (
        f"{surname or 'unknown'}_{year if year is not None else 'nodate'}_{first_word}"
    )
    key = base
    suffix = 2
    while key in taken:
        key = f"{base}_{suffix}"
        suffix += 1
    taken.add(key)
    return key


def format_authors(authors: str) -> str:
    """Converts a comma-separated author list into BibTeX `A and B` form."""
    names = [name.strip() for name in authors.split(",") if name.strip()]
    return " and ".join(names)


def is_publication(row: dict[str, Any]) -> bool:
    """Returns whether a Research row is a published paper that goes into papers.bib."""
    return (
        select_of(row, "유형") in PUBLICATION_TYPES
        and select_of(row, "상태") not in EXCLUDED_STATUSES
    )


def build_bibliography(research_rows: list[dict[str, Any]]) -> tuple[str, int]:
    """Renders the publication rows as a BibTeX file body."""
    entries: list[tuple[int, str, dict[str, Any]]] = []
    for row in research_rows:
        if not is_publication(row):
            continue
        title = english_title(row, "제목")
        year = number_of(row, "연도")
        entries.append((-int(year) if year is not None else 1, title, row))
    entries.sort(key=lambda item: (item[0], item[1]))

    taken: set[str] = set()
    blocks: list[str] = []
    for _, title, row in entries:
        entry_type, venue_field, label = PUBLICATION_TYPES[select_of(row, "유형")]
        year = number_of(row, "연도")
        authors = text_of(row, "저자")
        url = url_of(row, "URL")

        fields: list[tuple[str, str]] = [("pubtype", label)]
        abbr = text_of(row, "약칭")
        if abbr:
            fields.append(("abbr", abbr))
        fields.append(("title", title))
        if authors:
            fields.append(("author", format_authors(authors)))
        if venue_field and text_of(row, "게재처"):
            fields.append((venue_field, text_of(row, "게재처")))
        if year is not None:
            fields.append(("year", str(int(year))))
        doi = text_of(row, "DOI")
        if doi:
            fields.append(("doi", doi))
        if url:
            fields.append(("url", url))
            fields.append(("html", url))
        if checkbox_of(row, "대표"):
            fields.append(("selected", "true"))

        width = max(len(name) for name, _ in fields)
        lines = [f"@{entry_type}{{{bib_key(authors, year, title, taken)},"]
        lines += [f"  {name.ljust(width)} = {{{value}}}," for name, value in fields]
        lines.append("}")
        blocks.append("\n".join(lines))

    return "---\n---\n\n" + "\n\n".join(blocks) + ("\n" if blocks else ""), len(blocks)


# -----------------------------------------------------------------------------
# _projects
# -----------------------------------------------------------------------------


def project_period(status: str, start: str, end: str) -> str:
    """Builds a project period; an Ongoing project runs up to `present`."""
    return format_period(start, end, ongoing=status == "Ongoing")


def project_description(status: str, institution: str, start: str, end: str) -> str:
    """Builds `Status · institution · YYYY.MM – YYYY.MM`; empty parts are skipped."""
    period = project_period(status, start, end)
    return " · ".join(part for part in (status, institution, period) if part)


def cowork_description(row: dict[str, Any]) -> str:
    """Builds `venue · year` for Co-work research cards; skips empty parts."""
    year = number_of(row, "연도")
    parts = (text_of(row, "게재처"), str(int(year)) if year is not None else "")
    return " · ".join(part for part in parts if part)


def build_projects(
    project_rows: list[dict[str, Any]], research_rows: list[dict[str, Any]]
) -> list[tuple[str, str]]:
    """Renders project cards as (filename, content) pairs.

    Sources are the Projects database and the Co-work rows of the Research
    database. Co-work rows that are published papers are left out, since the
    research tab already lists them. Project bodies stay empty; only the
    front matter carries data.
    """
    drafts: list[dict[str, Any]] = []

    # Ongoing projects first, then the most recently started.
    ordered_projects = sorted(
        project_rows,
        key=lambda row: (
            select_of(row, "상태") == "Ongoing",
            date_of(row, "기간")[0] or "",
        ),
        reverse=True,
    )
    for row in ordered_projects:
        status = select_of(row, "상태")
        institution = text_of(row, "기관·발주처")
        start, end = date_of(row, "기간")
        drafts.append(
            {
                "row": row,
                "title": text_of(row, "프로젝트명"),
                "description": project_description(status, institution, start, end),
                # Separate fields so the home page can lay them out (status pill,
                # meta line) instead of printing the joined description.
                "fields": {
                    "status": status,
                    "institution": institution,
                    "period": project_period(status, start, end),
                },
                "importance": number_of(row, "중요도"),
                "category": PROJECT_CATEGORIES.get(
                    select_of(row, "분류"), DEFAULT_PROJECT_CATEGORY
                ),
            }
        )

    cowork_rows = [
        row
        for row in research_rows
        if select_of(row, "참여") == "Co-work" and not is_publication(row)
    ]
    ordered_cowork = sorted(
        cowork_rows,
        key=lambda row: (
            -int(number_of(row, "연도") or 0),
            english_title(row, "제목"),
        ),
    )
    for row in ordered_cowork:
        year = number_of(row, "연도")
        drafts.append(
            {
                "row": row,
                "title": english_title(row, "제목"),
                "description": cowork_description(row),
                "fields": {
                    "institution": text_of(row, "게재처"),
                    "period": str(int(year)) if year is not None else "",
                },
                "importance": None,
                "category": RESEARCH_PROJECT_CATEGORY,
            }
        )

    files: list[tuple[str, str]] = []
    used_slugs: set[str] = set()
    for index, draft in enumerate(drafts, start=1):
        front_matter: dict[str, Any] = {
            "layout": "page",
            "title": draft["title"],
        }
        if draft["description"]:
            front_matter["description"] = draft["description"]
        for key, value in draft["fields"].items():
            if value:
                front_matter[key] = value
        importance = draft["importance"]
        front_matter["importance"] = (
            int(importance) if importance is not None else index
        )
        front_matter["category"] = draft["category"]

        slug = slugify(draft["title"]) or short_id(draft["row"])
        if slug in used_slugs:
            slug = f"{slug}-{short_id(draft['row'])}"
        used_slugs.add(slug)

        body = dump_yaml(front_matter)
        files.append((f"{slug}.md", f"---\n{body}---\n\n{GENERATED_MARKER}\n"))
    return files


def write_projects(files: list[tuple[str, str]]) -> None:
    """Replaces the generated project files, leaving hand-written ones alone."""
    PROJECTS_DIR.mkdir(parents=True, exist_ok=True)
    for path in PROJECTS_DIR.glob("*.md"):
        if GENERATED_MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
    for name, content in files:
        (PROJECTS_DIR / name).write_text(content, encoding="utf-8")


# -----------------------------------------------------------------------------
# _data/education.yml and _data/honors.yml
# -----------------------------------------------------------------------------


def cv_rows_of(cv_rows: list[dict[str, Any]], kind: str) -> list[dict[str, Any]]:
    """Returns the CV rows of one 구분, most recently started first."""
    rows = [row for row in cv_rows if select_of(row, "구분") == kind]
    return sorted(
        rows,
        key=lambda row: (date_of(row, "기간")[0], text_of(row, "내용")),
        reverse=True,
    )


def build_education(cv_rows: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Builds the education list rendered by _includes/education_list.liquid.

    One mapping per degree, most recent first; empty fields are left out. The
    ``비고`` column is private (it holds student ids) and is never exported.
    """
    education: list[dict[str, str]] = []
    for row in cv_rows_of(cv_rows, "Education"):
        start, end = date_of(row, "기간")
        fields = {
            "degree": text_of(row, "내용"),
            "institution": text_of(row, "기관"),
            "period": format_period(start, end, ongoing=True),
        }
        education.append({key: value for key, value in fields.items() if value})
    return education


def build_honors(cv_rows: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Builds the honors list rendered by _includes/honors_list.liquid.

    One mapping per award, most recent first; empty fields are left out. As for
    the education list, the private ``비고`` column stays in Notion.
    """
    honors: list[dict[str, str]] = []
    for row in cv_rows_of(cv_rows, "Award"):
        fields = {
            "title": text_of(row, "내용"),
            "organization": text_of(row, "기관"),
            "amount": text_of(row, "규모"),
            "date": format_year_month(date_of(row, "기간")[0]),
        }
        honors.append({key: value for key, value in fields.items() if value})
    return honors


# -----------------------------------------------------------------------------
# _data/patents.yml
# -----------------------------------------------------------------------------


def build_patents(patent_rows: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Builds the patent list rendered by _includes/patent_list.liquid.

    One mapping per patent, most recently filed first; empty fields are left out.
    Dates stay ISO (YYYY-MM-DD) and are formatted in Liquid.
    """
    ordered = sorted(
        patent_rows,
        key=lambda row: (date_of(row, "출원일")[0], english_title(row, "발명의 명칭")),
        reverse=True,
    )
    patents: list[dict[str, str]] = []
    for row in ordered:
        fields = {
            # `Title (EN)` when filled, else the official (Korean) title.
            "title": english_title(row, "발명의 명칭"),
            "status": select_of(row, "상태"),
            "country": select_of(row, "국가"),
            "application_number": text_of(row, "출원번호"),
            "filed": date_of(row, "출원일")[0],
            "registration_number": text_of(row, "등록번호"),
            "registered": date_of(row, "등록일")[0],
            "applicant": text_of(row, "출원인"),
            "inventors": text_of(row, "발명자"),
        }
        patents.append({key: value for key, value in fields.items() if value})
    return patents


# -----------------------------------------------------------------------------
# _data/presentations.yml
# -----------------------------------------------------------------------------


def build_presentations(research_rows: list[dict[str, Any]]) -> list[dict[str, str]]:
    """Builds the presentation list rendered by _includes/presentation_list.liquid.

    One mapping per Research row with a ``발표 행사``, most recent first; empty
    fields are left out. The date is ``발표일`` as YYYY.MM.DD, else the year.
    """
    talks: list[tuple[str, str, dict[str, Any]]] = []
    for row in research_rows:
        if not text_of(row, "발표 행사"):
            continue
        title = text_of(row, "발표 제목") or text_of(row, "제목")
        day = date_of(row, "발표일")[0]
        year = number_of(row, "연도")
        when = day or (str(int(year)) if year is not None else "")
        talks.append((when, title, row))
    talks.sort(key=lambda item: (item[0], item[1]), reverse=True)

    presentations: list[dict[str, str]] = []
    for when, title, row in talks:
        fields = {
            "title": title,
            "authors": text_of(row, "저자"),
            "event": text_of(row, "발표 행사"),
            "location": text_of(row, "발표 장소"),
            "date": when.replace("-", "."),
            "type": select_of(row, "발표"),
        }
        presentations.append({key: value for key, value in fields.items() if value})
    return presentations


# -----------------------------------------------------------------------------
# Sync and self-check
# -----------------------------------------------------------------------------


def sync(include_private: bool) -> dict[str, int]:
    """Regenerates every artifact and returns the number of rows written."""
    token = read_token()
    research = query_database(token, RESEARCH_DB)
    projects = query_database(token, PROJECTS_DB)
    cv_entries = query_database(token, CV_DB)
    patents = query_database(token, PATENTS_DB)

    if not include_private:
        research = [row for row in research if is_public(row)]
        projects = [row for row in projects if is_public(row)]
        cv_entries = [row for row in cv_entries if is_public(row)]
        patents = [row for row in patents if is_public(row)]

    bib_text, bib_count = build_bibliography(research)
    BIB_PATH.parent.mkdir(parents=True, exist_ok=True)
    BIB_PATH.write_text(bib_text, encoding="utf-8")

    project_files = build_projects(projects, research)
    write_projects(project_files)

    education = build_education(cv_entries)
    EDUCATION_PATH.parent.mkdir(parents=True, exist_ok=True)
    EDUCATION_PATH.write_text(dump_yaml(education), encoding="utf-8")

    honors = build_honors(cv_entries)
    HONORS_PATH.write_text(dump_yaml(honors), encoding="utf-8")

    patent_list = build_patents(patents)
    PATENTS_PATH.write_text(dump_yaml(patent_list), encoding="utf-8")

    presentations = build_presentations(research)
    PRESENTATIONS_PATH.write_text(dump_yaml(presentations), encoding="utf-8")

    return {
        "publications": bib_count,
        "projects": len(project_files),
        "patents": len(patent_list),
        "presentations": len(presentations),
        "education": len(education),
        "honors": len(honors),
    }


def check() -> list[str]:
    """Re-reads the generated artifacts and returns a list of problems found."""
    problems: list[str] = []

    if not BIB_PATH.exists():
        problems.append(f"missing {BIB_PATH.relative_to(REPO_ROOT)}")
    else:
        text = BIB_PATH.read_text(encoding="utf-8")
        entries = re.findall(r"^@\w+\{", text, flags=re.MULTILINE)
        if not text.endswith("\n"):
            problems.append("papers.bib does not end with a newline")
        print(f"  papers.bib: {len(entries)} entries")

    for path, required in ((EDUCATION_PATH, "degree"), (HONORS_PATH, "title")):
        if not path.exists():
            problems.append(f"missing {path.relative_to(REPO_ROOT)}")
            continue
        try:
            entries = yaml.safe_load(path.read_text(encoding="utf-8"))
        except yaml.YAMLError as error:
            problems.append(f"{path.name} does not parse: {error}")
            continue
        if not isinstance(entries, list):
            problems.append(f"{path.name} is not a list")
        elif any(required not in entry for entry in entries):
            problems.append(f"{path.name} has an entry without a {required}")
        else:
            print(f"  {path.name}: {len(entries)} entries")

    if not PATENTS_PATH.exists():
        problems.append(f"missing {PATENTS_PATH.relative_to(REPO_ROOT)}")
    else:
        try:
            patents = yaml.safe_load(PATENTS_PATH.read_text(encoding="utf-8"))
        except yaml.YAMLError as error:
            problems.append(f"patents.yml does not parse: {error}")
        else:
            if not isinstance(patents, list):
                problems.append("patents.yml is not a list")
            elif any("title" not in patent for patent in patents):
                problems.append("patents.yml has an entry without a title")
            else:
                print(f"  patents.yml: {len(patents)} patents")

    if not PRESENTATIONS_PATH.exists():
        problems.append(f"missing {PRESENTATIONS_PATH.relative_to(REPO_ROOT)}")
    else:
        try:
            presentations = yaml.safe_load(
                PRESENTATIONS_PATH.read_text(encoding="utf-8")
            )
        except yaml.YAMLError as error:
            problems.append(f"presentations.yml does not parse: {error}")
        else:
            if not isinstance(presentations, list):
                problems.append("presentations.yml is not a list")
            elif any(
                field not in talk
                for talk in presentations
                for field in ("title", "event")
            ):
                problems.append(
                    "presentations.yml has an entry without a title or event"
                )
            else:
                print(f"  presentations.yml: {len(presentations)} presentations")

    generated = sorted(
        path
        for path in PROJECTS_DIR.glob("*.md")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")
    )
    for path in generated:
        text = path.read_text(encoding="utf-8")
        match = re.match(r"^---\n(.*?)\n---\n", text, flags=re.DOTALL)
        if not match:
            problems.append(f"{path.name}: no front matter")
            continue
        try:
            front_matter = yaml.safe_load(match.group(1))
        except yaml.YAMLError as error:
            problems.append(f"{path.name}: front matter does not parse: {error}")
            continue
        for field in ("layout", "title", "importance", "category"):
            if field not in front_matter:
                problems.append(f"{path.name}: front matter is missing '{field}'")
    print(f"  _projects: {len(generated)} generated files")

    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--all",
        action="store_true",
        help="include rows whose 공개 checkbox is off (preview only, do not commit)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the generated files after syncing and exit non-zero on failure",
    )
    args = parser.parse_args()

    counts = sync(include_private=args.all)
    scope = "all rows" if args.all else "public rows"
    print(
        f"synced {scope}: {counts['publications']} publications, "
        f"{counts['projects']} projects, {counts['patents']} patents, "
        f"{counts['presentations']} presentations, "
        f"{counts['education']} education, {counts['honors']} honors"
    )

    if not args.check:
        return 0

    print("checking generated files")
    problems = check()
    if problems:
        for problem in problems:
            print(f"  FAIL {problem}", file=sys.stderr)
        return 1
    print("check passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
